### ISSUE TITLE
Php's mail function will definitely hit spam. Try to use SMTP instead

### ISSUE THREAD

**Issue by markwbrown** [subins2000/logSys#12]
Php's mail function hits the spam folder almost all the time. Better to use SMTP. 
https://github.com/PHPMailer/PHPMailer/ Works wonders -- something like the following is a good stub out for a message that makes it to the inbox

`require_once('PHPMailerAutoload.php');
if ($conn->query($sql) === TRUE) {
    $mail = new PHPMailer();
    $mail->IsSMTP();
    $mail->SMTPAuth = true;
    $mail->Host = "mail.host.com";
    $mail->Port = 26;
    $mail->Username = "user@host.com";
    $mail->Password = "pass";
    $mail->SetFrom('from@host.com', 'Email Displayed Name');
    $mail->Subject = "Message Subject | Verification";
    $body = '<html><body>
    <h1>Just an example</h1>
    </body></html>';
    $mail->MsgHTML($body);
    $mail->AddAddress($email, $name);
    if($mail->Send()) {
      // do nothing, or something if you want
    } else {
      echo "Mailer Error: " . $mail->ErrorInfo;
    }
} else {
        echo "Error: " . $sql . "<br>" . $conn->error;
    }`

**Comment by subins2000** [comment]
Added instruction in README : https://github.com/subins2000/logSys/commit/45c00e49d3327e148fe58deaa9580e8c9958fd4b
