### ISSUE TITLE
Unable to submit login unless "Remember Me" is checked

### ISSUE THREAD

**Issue by markwbrown** [subins2000/logSys#13]
Unless checking "Remember Me" checkbox, user is not actually logged into the home.php destination page.

**Comment by subins2000** [comment]
I don't have this bug. How can one reproduce this bug ?

**Comment by markwbrown** [comment]
check out the demo at www.haticlabs.com

**Comment by subins2000** [comment]
@markwbrown By looking at the site cookies, I can see that PHP session cookie is not present.

Note that PHP Session is required by logSys to work. Either you call ```session_start();``` manually or set `config` -> `features` -> `start_session` to ```TRUE```

**Comment by markwbrown** [comment]
I already have start_session set to true.

**Comment by markwbrown** [comment]
If you look at the cookie logSyslogin, it has a domain of .haticlabs.com. On line 172 of class.logsys.php, I have "domain" => "haticlabs.com",

**Comment by subins2000** [comment]
That's a weird error. On my local server with subdomains, the bug doesn't seem to happen.
Are you using the latest version of logSys : https://github.com/subins2000/logSys/blob/master/class.logsys.php

Also, do a `var_dump($_SESSION);` after logging in. I'm wondering whether the variables are set.

Also, how are you setting the configuration ? Do not do it directly in the class.logsys.php file, instead use config.php file and pass the config array to `\Fr\LS::config($array)`

**Comment by markwbrown** [comment]
Sweet as. Reset class.logsys.php to default values and dumped session variables. (I had filled in domain under cookie-- and I think that is what was causing the error)
