### ISSUE TITLE
Function getUser doesn't take an array 

### ISSUE THREAD

**Issue by nagarjuna993** [subins2000/logSys#18]
The present getUser function only takes a string if the parameter is `$what = "*"`. So change it to the following `getUser($what, $user = null)`

**Comment by subins2000** [comment]
What are you proposing ?

**Comment by nagarjuna993** [comment]
I mean `getUser` function isn't taking an array for the `$what` parameter because you assigned it as string `$what = "*"` but the function has an option to pass an array to the `what` parameter, so simply change the function parameter to this `getUser($what, $user = null)`

**Comment by subins2000** [comment]
If one wants to just get a single column, he/she can pass the column name to `$what`. If he/she wants multiple columns, pass an array and if he/she wants everything, pass "*" or leave the param.

So, I don't think the default value (`*`) needs to be omitted.
