### ISSUE TITLE
Example Page

### ISSUE THREAD

**Issue by anjesh12** [subins2000/logSys#21]
Hey, i really like this login system, and wanted to use it for a login page. However i ran into ( yes head first) a problem. I keep getting the error "Fatal error: Call to a member function prepare() on null in /var/www/html/log/LS.php on line 890" when i try to register. and "Fatal error: Call to a member function prepare() on null in /var/www/html/log/LS.php on line 579" when trying to login. I dont know much about php, hope someone can help.

**Comment by subins2000** [comment]
* Read [this](http://subinsb.com/php-logsys#Fatal-error-Call-to-a-member-function-prepare-on-a-non-object)
* [Common Problems & Solutions](http://subinsb.com/php-logsys#Common-Problems)
