### ISSUE TITLE
Email Settings.

### ISSUE THREAD

**Issue by eddiethejibson** [subins2000/logSys#22]
Hi,

Just looking at the code, I can't see where the email settings are (SMTP) for things like reset password are. In the reset password PHP file, it it requires is the config file which has nothing to do with the email settings.

Any idea how l would configure the email settings with say SMTP?

Thanks @subins2000

**Comment by subins2000** [comment]
You can add an [email callback](http://subinsb.com/php-logsys#Sending-E-Mails) from where you send the email.

By default, logSys uses `mail()` function for sending emails.
