### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by chemsaravanan** [subins2000/logSys#23]
Hi subin,
In addition to reset password by the user (sending token and validating), please share how admin user reset password of any user by himself and share it to the concerned user. 

This will help the administrator to reset password even internet is not connected. In this case, the administrator will be retaining the registration form in his authentication.

Hope you understand the problem.

Can you help me so as to initiate my project work at the earliest?

**Comment by subins2000** [comment]
You can directly use the [`changePassword()`](https://subinsb.com/php-logsys#change-password) function to change the password without knowing the existing one.
