### ISSUE TITLE
I keep getting warning so script doesnt work

### ISSUE THREAD

**Issue by jackttcoms** [subins2000/logSys#24]
Warning: Cannot modify header information - headers already sent by ... LS.php on line 1054 
/src/LS.php on line 618 
/src/LS.php on line 1270

what should i do thanks (awesome script)

**Comment by subins2000** [comment]
Read this section please : http://subinsb.com/php-logsys#session-start-8211-headers-already-sent

**Comment by jackttcoms** [comment]
Ok where do i put that code because it doesnt say what page and also wouldnit solve the problem if i just change this to       "start_session" => false, or does it have to be on true

thanks

**Comment by jackttcoms** [comment]
'Cannot modify header information

You may have to enable Output Buffering to solve this problem. **Or you should move all your logSys and redirection function calls at the top of the page before any output is made.**' how do i do this, do i move all the header to the top of the LS.php file  because my stupid hosting don't support the htaccess or .ini files

thanks in advamce

**Comment by subins2000** [comment]
You should move logSys function calls before any output is made. Example :

```
<?php
require 'vendor/autoload.php';
// logSys calls here
// Output means the HTML code and other text that is printed.
?>
<html>
```
