### ISSUE TITLE
brute_force not working

### ISSUE THREAD

**Issue by jmichelot** [subins2000/logSys#29]
I couldn't make brute_force 'tries' parameters to work. When reviewing your code, I had to change : 
`$status        = (int) $cols[$this->config['db']['columns']['attempt']];`to : 
`$status        = $cols[$this->config['db']['columns']['attempt']];` (line 639)

and add : 

`else {
              $status = (int)$status;
            }
` after line 658.

Could you confirm and update the LS.php file ?

**Comment by subins2000** [comment]
Thank you @jmichelot for reporting this serious bug. It has been fixed. :)
