### ISSUE TITLE
0.9.1 No Token emails

### ISSUE THREAD

**Issue by saintnic** [subins2000/logSys#30]
I have attempted updating to 0.9.1 including changing the login page code but I cannot get any emails containing the token.
 
I have checked config.php and your revised LS.php appears to be ignoring lines config.php 41 – 45 as changing the instruction text does not appear on the login page as the content appears to come from hard code on the login page.
 
I have also tried putting various forms of email_callback in config.php again to no avail.
 
I have compared the relevant sections of LS 08 and LS 09 and again cannot see where it is failing.
 
Any guidance would be appreciated as I have had to rollback to 08.
I have attempted updating to 0.9.1 including changing the login page code but I cannot get any emails containing the token.
 
I have checked config.php and your revised LS.php appears to be ignoring lines config.php 41 – 45 as changing the instruction text does not appear on the login page as the content appears to come from hard code on the login page.
 
I have also tried putting various forms of email_callback in config.php again to no avail.
 
I have compared the relevant sections of LS 08 and LS 09 and again cannot see where it is failing.
 
Any guidance would be appreciated as I have had to rollback to 08.

**Comment by saintnic** [comment]
The problem lies in lines 1567-1582 where single quotes have replaced double quotes in the $headers[] lines.

If I replace these with those from 08 lines 1275-1288 I get my emails.

**Comment by subins2000** [comment]
That's a weird bug. I don't think the change from the double quotes to single is the root of this problem, because it [works fine](https://demos.subinsb.com/php/loginSystem/) for me with single quotes.

It might be something else with your setup.

1. What do you have in `config` -> `two_step_login` -> `send_callback` ?
2. Try debugging the email_callback. Add some echo lines to it and try logging in. Is there any output made ?

**Comment by saintnic** [comment]
config -> two_step_login -> send_callback
my config.php is exactly yours from the examples directory with the addition of a . "From: to $LS->sendMail to avoid emails going to Junk.
As I do not use anything other than the basic PHP Mail function setting an email_callback stops emails being sent I do not set an email_callback'
