### ISSUE TITLE
managing Devices

### ISSUE THREAD

**Issue by saintnic** [subins2000/logSys#31]
As you now use time() rather than now() in the last_access column and no formatting is performed on the manage0devices page this makes it somewhat difficult to choose device to revoke.

**Comment by subins2000** [comment]
Yeah, this is in case of `two-step-login` example.

In the [`material-design` example](https://github.com/subins2000/logSys/blob/master/examples/material-design/manage-devices.php#L45), it's displayed as a normal date.
