### ISSUE TITLE
Problem in LS.php

### ISSUE THREAD

**Issue by simonevolpini** [subins2000/logSys#32]
Hallo,
I think I found a mistake in row 949 of LS.php.
now is:
$this->sendResetPasswordToken($cols['id']);

but the correct row is:
$this->sendResetPasswordToken($cols[$this->config['db']['columns']['id']]);

Bye,
Simone

**Comment by subins2000** [comment]
Yes. It's a mistake. Thanks for pointing it out. I have fixed it.

**Comment by simonevolpini** [comment]
thanks to you :)
