### ISSUE TITLE
Composer Install Issue

### ISSUE THREAD

**Issue by spindriftwebs** [subins2000/logSys#33]
Hi, I am getting the following error when running

`composer require francium/logsys`

Problem 1
    - Installation request for francium/logsys ^1.0 -> satisfiable by francium/logsys[v1.0].
    - francium/logsys v1.0 requires duncan3dc/sessions dev-master -> satisfiable by duncan3dc/sessions[dev-master] but these conflict with your requirements or minimum-stability.

What do I need to do please ?

**Comment by subins2000** [comment]
You'll need to add `"minimum-stability": "dev"` to your composer.json file before you install the package.

**Comment by martyngommans** [comment]
Hi, I am getting the following error on mac

[Composer\Downloader\TransportException]                                     
  The "http://packagist.org/p/francium/logsys%24f3eee0df92cd7fb5e66cc1528e837  
  e62eb2d0be4ade2d0c9beceaa999c11a9f3.json" file could not be downloaded: SSL  
   operation failed with code 1. OpenSSL Error messages:                       
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify   
  failed                                                                       
  Failed to enable crypto                                                      
  failed to open stream: operation failed

**Comment by subins2000** [comment]
logSys don't need dev minimum stability anymore.
