### ISSUE TITLE
Warning: openssl_decrypt(): IV passed is only 15 bytes long

### ISSUE THREAD

**Issue by theraw** [subins2000/logSys#36]
i just checked "remeber me" and i started to see this warn
```php
Warning: openssl_decrypt(): IV passed is only 15 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0 in LS.php on line 520
```

Also i have another question, is there anyway how to use a personal smtp server? because from docs didn't found something about this :confused: or i haven't read carefully

**Comment by reddingwebpro** [comment]
This appears to still be an issue. When using Chrome on my desktop it works fine, but this error is still present using any browser on an iPad (since even Chrome on an iPad ultimately still uses Safari behind the scenes).

**Comment by theraw** [comment]
Sorry i don't have time to test this also i don't se reopen button on my phone :confused:

**Comment by TechOverflow** [comment]
I am encountering this problem on MacOS Safari. I'm not sure if its browser specific, but I can do some testing. It doesn't happen always, only say once every 3-5 logins and I just have to re-login to get rid of the Warning.
