### ISSUE TITLE
No token emails when using PHP mail not email_callback

### ISSUE THREAD

**Issue by saintnic** [subins2000/logSys#37]
I raised this with 0.9.1 back in September 2017 as I do not use a mailer but the basic PHP mail function.

I eventually resolved the problem by replacing single quotes with double in the headers section of 
   public function sendMail($email, $subject, $body){
and everything worked fine in 0.9.1.

Today I have managed to upgrade to 1.0.1 after much anguish with Composer only to find again no tokens were being sent to user.

I have therefore replaced lines 1623 - 1639 with the those from 0.9.1 and I GET MY TOKEN EMAILS.

Lines used from 0.9.1
    public function sendMail($email, $subject, $body){
    /**
     * If there is a callback for email sending, use it else PHP's mail()
     */
    if(is_callable($this->config['basic']['email_callback'])){
      $that = $this;
      call_user_func_array($this->config['basic']['email_callback'], array(&$that, $email, $subject, $body));
    }else{
      $headers = array();
      $headers[] = "MIME-Version: 1.0";
      $headers[] = "Content-type: text/html; charset=iso-8859-1";
      $headers[] = "From: ". $this->config['basic']['email'];
      $headers[] = "XXReply-To: ". $this->config['basic']['email'];
      mail($email, $subject, $body, implode("\r\n", $headers));

        }
    }

You will see the double quotes again!!

Could you please have another look at this frustrating issue that arises with each upgrade as all that has really changed is LS.php and the inclusion of the duncan3dc files.

I know you

**Comment by subins2000** [comment]
Instead of directly changing the `LS.php` file, you can add an email callback to the config :
```php
new Fr\ClassName(array(
  "basic" => array(
    "email_callback" => function($LS, $email, $subject, $body){
        $headers = array();
        $headers[] = "MIME-Version: 1.0";
        $headers[] = "Content-type: text/html; charset=iso-8859-1";
        $headers[] = "From: ". $this->config['basic']['email'];
        $headers[] = "XXReply-To: ". $this->config['basic']['email'];
        mail($email, $subject, $body, implode("\r\n", $headers));
    }
  )
));
```

**Comment by saintnic** [comment]
Thanks for the concept.
Using $this in From and Reply to generates a fatal error:Fatal error: Uncaught Error: Using $this when not in object context in /volume1/web/config/config.php:17 Stack trace: #0 [internal function]: {closure}(Object(Fr\LS),
However replacing the From and Reply to with hard coded email address works.
Thx Again.

**Comment by subins2000** [comment]
Oops, forgot that part. Yeah, `$this` can't be used there. Mentioning the email directly is the way to go.

**Comment by saintnic** [comment]
Thanks again
