### ISSUE TITLE
Setting Up PHPMailer

### ISSUE THREAD

**Issue by spindriftwebs** [subins2000/logSys#39]
Hi, I'm struggling to setup the smtp delivery using PHPMailer.  I have installed PHPMailer using composer and have amended the namespace includes in LS.php as follows:

```
use duncan3dc\Sessions\SessionInstance;
use phpmailer\phpmailer\PHPMailer;
use phpmailer\phpmailer\Exception;
use Fr\LS\TwoStepLogin;
use PDO;
use PDOException;
```

In the callback function I have:

`$mail = new PHPMailer(true); `

I keep getting the error:

Fatal error: Class 'phpmailer\phpmailer\PHPMailer' not found in public_html/vendor/francium/logsys/src/Fr/LS.php on line 1652

I'm not sure what it wrong because I have uploaded the amended vendor file since installing PHPMailer.  

Any help would be appreciated.  Thanks.

Guy

**Comment by subins2000** [comment]
Please use the `email_callback` config value for sending emails using a custom function : https://subinsb.com/php-logsys/#sending-e-mails
