### ISSUE TITLE
Sqlite support problems

### ISSUE THREAD

**Issue by maplewang** [subins2000/logSys#41]
in LS.php line 449
` 
 try {
            if ($this->config['db']['type'] === 'sqlite') {

                $this->dbh = new PDO(

                    'sqlite:' . $this->config['db']['sqlite_path'],

                    $this->config['db']['username'],

                    $this->config['db']['password'],

                    array(

                        PDO::ATTR_PERSISTENT        => true,

                        PDO::ATTR_ERRMODE           => PDO::ERRMODE_EXCEPTION,

                        PDO::ATTR_STRINGIFY_FETCHES => true,

                    )  
 );`

pdo opens sqlite should include full path of sqlite db together with sqlite db file name.
sqlite_path make us think it is only path.

another should thing is that it should include db type in config.php

    'db'       => array(
		'type'		=> 'sqlite',
		'sqlite_path' => 'c:\db\Logsys.db',`

**Comment by subins2000** [comment]
If you look at the doc, it mentions that `sqlite_path` should be absolute : http://subinsb.com/php-logsys/#db

The doc also mentions the `type` config param.
