### ISSUE TITLE
Click behaviors

### ISSUE THREAD

**Issue by Ivan367al** [subins2000/logSys#44]
Hello there! I'd like to ask about a strange behavior of the buttons in the main page: clicking on both sign in and register btns, the only change is the address on the address bar, the right one, but the page is not loaded. I have to go to the address bar, click and <Enter>, then the page come up.
The buttons in the header are both NOT working as well (same behaviour as before)
The button in the register page is actually working.

**Comment by subins2000** [comment]
It's a bug with the example `material-design`. You may use the other examples.

**Comment by Ivan367al** [comment]
Thanks alot, Subin! By the way, you did a very good job!
On the right way to be a very good php programmer!

Kind regards
   Ivano

Il giorno mar 8 gen 2019 alle ore 18:39 Subin Siby <notifications@github.com>
ha scritto:
