### ISSUE TITLE
Session not working after login

### ISSUE THREAD

**Issue by umaraliunique** [subins2000/logSys#8]
I sign in and redirect to home page and then I go back or move to sign in page it opens but actually it should not be open because user is already login he didn't logout.

**Comment by subins2000** [comment]
When you click "Back" button in browser, it loads the cached page (the login page). If you do a reload on the login page, then you would be redirected to home page.
If you want to change this default behavior of browser, then you must do AJAX request on every pages checking whether user is logged in or not.
