### ISSUE TITLE
Unable to log out.

### ISSUE THREAD

**Issue by markwbrown** [subins2000/logSys#9]
While logged in and on home.php, clicking "Log Out" for logout.php yields:

Warning: session_destroy(): Trying to destroy uninitialized session in /path/to/dir class.logsys.php on line 541

Any further navigation keeps one logged in unless the cookies are deleted. This may be due to not being able to submit login form without "Remember Me" checked and features =>array "remember_me" set to true

**Comment by markwbrown** [comment]
Logout issue fixed with proposed merge.

**Comment by subins2000** [comment]
@markwbrown Check whether ````config` -> `features` -> `start_session```` is set to TRUE. If it is, then the error won't be produced. Otherwise you would have to manually call ```session_start()```
